modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="animacionesglitch"
version="1.0.0"
displayName="Animaciones Glitch"
description='''Animaciones con glitch rojo en pantalla cuando un jugador pierde una vida o es eliminado.'''

[[dependencies.animacionesglitch]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.animacionesglitch]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
